parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '10.7'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Core\Domain\Entity:
                type: xml
                dir: '%kernel.project_dir%/src/Core/Infrastructure/Persistence/Doctrine/Mapping/Domain'
                is_bundle: false
                prefix: App\Core\Domain\Entity
                alias: Entity

            App\GP\Domain\Entity:
                type: xml
                dir: '%kernel.project_dir%/src/GP/Infrastructure/Persistence/Doctrine/Mapping/Domain'
                is_bundle: false
                prefix: App\GP\Domain\Entity
                alias: Entity
