framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    property_info:
        enabled: true
    translator:
        enabled: true
        fallbacks: ['en']
    #csrf_protection: true
    #http_method_override: true
    #esi: true
    #fragments: true
    php_errors:
        log: true
    cache:
        prefix_seed: '%env(APP_HOST)%_'
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
    validation:
        mapping:
            paths:
                - '%kernel.project_dir%/src/Core/Domain/Validation/validation.yaml'
